version: '3'
services:
  bitcoind:
    image: hojarasca/bitcoinsv-regtest:1.0.10
    volumes:
      - bitcoind-data:/bitcoin/data
    environment:
      RPCUSER: rundb
      RPCPASSWORD: rundb
    ports:
      - 18332:18332
      - 28332:28332

  main-run-db:
    build:
      context: .
    command: ["npm", "start"]
    volumes:
      - ./src:/app/src
      - run-db-data:/data
    environment:
      DB: /data/run-db.sqlite3
      BITCOIN_RPC_URL: http://rundb:rundb@bitcoind:18332
      ZMQ_URL: tcp://bitcoind:28332
      START_HEIGHT: 0
      WORKERS: 1
      PORT: 3000
      NETWORK: test
      API: ${API}
      EXECUTOR: ${EXECUTOR}
      EXECUTE_ENDPOINT:

  execution-server:
    build:
      context: .
    command: [ "npm", "start-execution-server" ]
    volumes:
      - ./src:/app/src
      - run-db-data:/data
    environment:
      WORKERS: 2
      PORT: 3001
      NETWORK: test
      DATA_API_TX_ROOT: ${DATA_API_TX_ROOT}
      DATA_API_STATE_ROOT: ${DATA_API_STATE_ROOT}

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: someuser
      POSTGRES_PASSWORD: sosecret
      POSTGRES_DB: rundb_regtest
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./dev/create-dbs.sh:/docker-entrypoint-initdb.d/create-dbs.sh

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
#      - ./dev/rabbitmq.conf:/etc/rabbitmq/conf.d/10-default-guest-user.conf
    ports:
      - 5674:5672
      - 15674:15672

volumes:
  bitcoind-data:
  rabbitmq-data:
  run-db-data:
  db-data: