name: tests

on: push

jobs:
  cover_tests:
    name: Cover Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Setup Node 16
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Dependencies
      id: cache-node-modules
      uses: actions/cache@v1
      env:
        cache-version: 1
      with:
        path: node_modules
        key: v${{ env.cache-version }}-node16-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

    - name: Install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install -y tar
        yarn install

    - name: Lint
      run: yarn run lint

    - name: Cover Tests
      run:
        yarn run test:cover

    - name: Publish Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage/lcov.info

  node_12_tests:
    name: Node 16 Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Setup Node 16
      uses: actions/setup-node@v1
      with:
        node-version: '16.14.0'

    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Dependencies
      id: cache-node-modules
      uses: actions/cache@v1
      env:
        cache-version: 1
      with:
        path: node_modules
        key: v${{ env.cache-version }}-node16-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

    - name: Install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install -y tar
        yarn install

    - name: Test Node
      run: yarn run test